Github Actions: Build with OpenSSL3

diff --git a/.github/workflows/build_openssl3.yml b/.github/workflows/build_openssl3.yml
--- a/.github/workflows/build_openssl3.yml
+++ b/.github/workflows/build_openssl3.yml
@@ -25,19 +25,33 @@ jobs:
           ./Configure shared no-ssl2 no-ssl3 --prefix=$GITHUB_WORKSPACE/openssl_3.0.0_installed
           make all install_sw VERSION="3.0.0"
 
-      - name: Build release package
+      - name: Build
         run: |
           set -e -o pipefail
           set -x
 
           export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/openssl_3.0.0_installed/lib64/pkgconfig
           mkdir build; cd build
-          cmake ..
+          cmake .. -DWITHOUT_MANPAGES=1
           make
+
+      - name: Test
+        run: |
+          wget -q https://github.com/square/ghostunnel/releases/download/v1.3.1/ghostunnel-v1.3.1-$(uname -s | tr '[:upper:]' '[:lower:]')-amd64-with-pkcs11 -O /tmp/ghostunnel
+          chmod +x /tmp/ghostunnel
+          openssl aes-256-cbc -k "$tlspwd" -md sha256 -in ./.ci/client-combined.pem.enc -out ./.ci/client-combined.pem -d
+          /tmp/ghostunnel client --listen localhost:12345 --target hsm-connector01.sthlm.in.yubico.org:8443 --keystore ./.ci/client-combined.pem --cacert ./.ci/server-crt.pem 2>/dev/null &
+          sleep 3
+          DEFAULT_CONNECTOR_URL=$(curl -s http://localhost:12345/dispatcher/request)
+          test -n "$DEFAULT_CONNECTOR_URL" || (echo "Unable to obtain a connector URL, aborting"; exit 1)
+          echo $DEFAULT_CONNECTOR_URL
+          echo "DEFAULT_CONNECTOR_URL=$DEFAULT_CONNECTOR_URL" >> $GITHUB_ENV
+
+          ./src/yubihsm-shell --connector "$DEFAULT_CONNECTOR_URL" -p password -a reset
 
 
   macos:
-    name: Build MacOS
+    name: Build MacOS OpenSSL 3
     runs-on: macos-10.15
     steps:
       - name: checkout
